### ISSUE TITLE
Did not run, tried everthing...

### ISSUE THREAD

**Issue by mdelgadov** [FabianGosebrink/ASPNETCore-Angular-SignalR-Typescript#6]
Hello, I liked your solution very much. It mixes state of the art tech and is very valuable.

But I can't make it run though. I follow your steps and all run properly.

The problem is the wwwroot never gets the bundle, it stays in .dist
Which makes me think, is there a step to copy the bundle from .dist to wwwroot that I don't know about?

Thanks in advance for your help and again, great repo...

**Comment by FabianGosebrink** [comment]
Hey mdelgadov,

the wwwroot.folder contains the development files. So if you press the "Play" button in Visual Studio it should run in your browser. The gulp-tasks are only for distributing.

So if you run these tasks the ".dist"-Folder will be created and in there you will find your files to deliver to the customer etc.

Does this make the thing clear to you?

Best regards

Fabian

**Comment by mdelgadov** [comment]
Thanks for your response, I get amazed by your repo more and more... if only it worked... not your fault... I'm missing something, don't know what...
This is the state:

I cloned,
I npm installed
I do dnx web

All the info messages show.

all looks fine except: 
![untitled](https://cloud.githubusercontent.com/assets/1537551/16098482/2d6fb13e-3321-11e6-97ae-3148eb85e4fd.png)

As you can see, the app.bundle doesn't show, now, the dist/app.bundle is usually created by gulp (usually, and you do that for other folders, the dist you mention)

I also compiled and ran the dist versions and they call properly but without the servers they show just the search sections on the left. 

Which makes me wonder, how do I run the signal r projects? I tried to run them from the solution properties but didn't help:
![untitled2](https://cloud.githubusercontent.com/assets/1537551/16098638/217e8e12-3322-11e6-9dc7-4f08130fba6b.png)
of course, this answered:
![untitled](https://cloud.githubusercontent.com/assets/1537551/16098645/2bac3d12-3322-11e6-9c4c-b6d3bfb11255.png)

Finally I ran all the gulp tasks and non created the bundle, my next step will be to create my own gulp task to create the bundle... not a big deal, but without the signal r server running, I don't know if this going to go any further...

![untitled2](https://cloud.githubusercontent.com/assets/1537551/16098721/83868286-3322-11e6-9631-29f77c561a62.png)

I appreciate any pointer you may have, thanks again.

Miguel

**Comment by FabianGosebrink** [comment]
Ah now I see.
Well, the solution is not meant to be started via the "play" button in Visual Studio (VS). Its more like: Build the web-app via gulp, start the web server and start the generated web app. I did not make that clearly in the readme.md. I'm sorry. 

As I moved to webpack I kind of lost the ability in VS to press "Play" and let it run.

You have two possibilities here:
If you want to press "Play" in VS you have to configure webpack to move the files to the desired place. So you can change this line (11) `filename: "[name].bundle.js"` to this line `filename: "./wwwroot/dist/[name].bundle.js"` which will cause webpack to build at the place where asp.net is looking for it. Copy the jquery file manually too to have that functionality.

The second option is to: Build the webapp via gulp, start the server via `dnx web` , start the webapp via doubleclicking the index.html and it should run. But not out of VS so far.

I am trying to find a cool solution to this. Perhaps I will introduce a webpack.dev.config for making it starting out of VS and a webpack.prod.config which deploys to the dist-folder.

The SignalR-Projects **are not meant to be run**. They are only for having the latest Signalr3-things because there were problems including them via nuget. They are just for having the code and consuming it.

I hope this is helping you.

Best regards
Fabian

**Comment by mdelgadov** [comment]
Thanks Fabian, really helped me... closing this now...
