### ISSUE TITLE
Jquery.signalr.js is missing

### ISSUE THREAD

**Issue by cveld** [FabianGosebrink/ASPNETCore-Angular-SignalR-Typescript#8]
Fantastic work you have done with this repo! Just logging this issue with some issues I experienced.

I did the following:
- Clone this repo
- Open up Visual Studio
- Run `gulp build:all` 
- Start the project through Visual Studio

I experienced the following:
- The startup project was `Microsoft.AspNet.SignalR.Messaging`. I have changed this to `AspNetCoreAngular2`
- IIS Express is looking into the `wwwroot`-folder but the build process outputs its files to the folder `.dist`. The file `index.html` does not contain correct references; 
- `jquery.signalr.js` is missing in both folders (`wwwroot` and `.dist`). I had to copy it manually. I was expecting this file was bundled by the webpack process or some gulp task, which currently is not. Any idea how to solve this? I am currently looking into the npm package `signalr-amd`. Ideally one references some module from `vendor.ts`.

Additionally, some considerations:
- I was expecting webpack or some gulp task being attached to the Task Runner's Project Open or After Build event. What is your opinion on this?
- I would expect some webpack watch process being in place to enable a fast ctrl-s experience. What are your thoughts on this?
- The usage of `dnx web`. I believe this is replaced by `dotnet run` now? If I try that (using CLI version `1.0.0-preview1-002702` from rc2), I get a single line output `2. The project does not support the desired framework:`.

**Comment by FabianGosebrink** [comment]
First of all: Thank you for letting me know.

In your mentioned steps you forgot to run "npm install" which I mentioned in the readme. You also forget to run "bower install" which is needed for the jquery signalR. I did not mention that yet, so I will fix this in the readme. Thanks for pointing :)

I am not quite sure but sometimes when you clone this repo for the first time the startup-project is not set correctly. So you have to do this manually AFAIK. I will also mention that in the readme to avoid conflicts.

> IIS Express is looking into the wwwroot-folder but the build process outputs its files to the folder .dist. The file index.html does not contain correct references; 

This is kind of interesting because everybody wants to run this solution out of Visual Studio which it was never supposed to build for. :) Don't get me wrong: This is more my fault then yours but I never thought about it because I am only developing server-side things in Visual Studio directly and use VSCode for client side development. So I never press the "Play"-Button in VS.

What I will check in is a development-task which will copy the right things into the wwwroot. So then you can drive this gulp task and run the solution out of Visual Studio.

> jquery.signalr.js is missing in both folders (wwwroot and .dist). I had to copy it manually. I was expecting this file was bundled by the webpack process or some gulp task, which currently is not. Any idea how to solve this? 

Yes I have. I will solve this :)

> I was expecting webpack or some gulp task being attached to the Task Runner's Project Open or After Build event. What is your opinion on this?

The Task-Runner from VS itself is handling the gulp-files. For webpack I needed to install an extension. I was not able to get _both_ task runners appear in the task-runner window (But I am working on it). If this is working I will point an after-build-event to the introduced development-task and it should run smoothly.

> I would expect some webpack watch process being in place to enable a fast ctrl-s experience. What are your thoughts on this?

You can use the webpack-dev-server for this.

> The usage of dnx web. I believe this is replaced by dotnet run now? If I try that (using CLI version 1.0.0-preview1-002702 from rc2), I get a single line output 2. The project does not support the desired framework:.

The repo is _not_ updated to ASP.NET Core so far. I will do that in a seperate task. It will have Version 1.0.0 then and will run with the dotnet-cli.

I hope I could point some things out! Once again: Thank you for your message and thoughts.

HTH

Best Regards

**Comment by cveld** [comment]
Fabian, thanks for the extensive answers :)

What would be the benefit of using Visual Studio Code for the web
development part?

Can you explain how you will proceed with integrating jquery.signalr.js
more? Just a simple gulp copy task or will you work with some webpack AMD
flow?

Can you explain how I could use webpack-dev-server in combination with the
ASP.NET Core webapi's that need to run?

BTW: npm install and bower install are automatically kicked off when the
project is opened in Visual Studio. So I was able to just copy the missing
jquery.signalr.js from the bower folder towards .dist and/or wwwroot.

2016-06-30 8:05 GMT+02:00 Fabian Gosebrink notifications@github.com:

**Comment by FabianGosebrink** [comment]
Hallo cveld,

> What would be the benefit of using Visual Studio Code for the web development part?

Its more lightweight and VS is IMHO not build for writing html/js/ts etc. VSCode is especially build for that. But drive with the tools you can drive best. It's up to you. Just know that you do not _have to_ use VS to build client-side apps.

> Can you explain how you will proceed with integrating jquery.signalr.js more? Just a simple gulp copy task or will you work with some webpack AMD flow?

Its a gulp task. Already checked in.

> Can you explain how I could use webpack-dev-server in combination with the ASP.NET Core webapi's that need to run?

If you typed "npm install" you already have the dev-server installed. You can simply start it via "webpack-dev-server --inline --progress --port 8080" for example. Then open up the browser and browse to the link. You can also see my other repo [Foodchooser - Angular 2 ASP.NET](https://github.com/FabianGosebrink/ASPNET-Foodchooser-Cross-Platform-Angular2) for example and this blogpost is also not the biggest mistake IMHO [blog](http://offering.solutions/articles/angular/cross-platform-builds-with-angular2-gulp-and-webpack/)

but with the dev-server you have to start the ASP.NET part manually first. 

> BTW: npm install and bower install are automatically kicked off when the project is opened in Visual Studio. So I was able to just copy the missing jquery.signalr.js from the bower folder towards .dist and/or wwwroot.

You are right. But I can not be sure everybody (!) using this repo is using VS or especially VS2015 :)

I do close this now because "Jquery.signalr.js is missing" should be done.

Best regards
